export const allLanguages = [
    { code: 'smart_auto', name: '智能自动 (Smart Auto)' },
    { code: 'zh', name: '中文 (Chinese)' },
    { code: 'en', name: 'English' },
    { code: 'ru', name: 'Русский (Russian)' },
    { code: 'ka', name: 'ქართული (Georgian)' },
    { code: 'hy', name: 'Հայերեն (Armenian)' },
    { code: 'ja', name: '日本語 (Japanese)' },
    { code: 'ko', name: '한국어 (Korean)' },
    { code: 'fr', name: 'Français (French)' },
    { code: 'de', name: 'Deutsch (German)' },
    { code: 'es', name: 'Español (Spanish)' },
    { code: 'pt', name: 'Português (Portuguese)' },
    { code: 'it', name: 'Italiano (Italian)' },
    { code: 'af', name: 'Afrikaans' },
    { code: 'sq', name: 'Shqip (Albanian)' },
    { code: 'am', name: 'አማርኛ (Amharic)' },
    { code: 'ar', name: 'العربية (Arabic)' },
    { code: 'az', name: 'Azərbaycan (Azerbaijani)' },
    { code: 'eu', name: 'Euskara (Basque)' },
    { code: 'be', name: 'Беларуская (Belarusian)' },
    { code: 'bn', name: 'বাংলা (Bengali)' },
    { code: 'bs', name: 'Bosanski (Bosnian)' },
    { code: 'bg', name: 'Български (Bulgarian)' },
    { code: 'ca', name: 'Català (Catalan)' },
    { code: 'ceb', name: 'Cebuano' },
    { code: 'ny', name: 'Chichewa' },
    { code: 'zh-TW', name: '中文 (繁體) (Traditional Chinese)' },
    { code: 'co', name: 'Corsu (Corsican)' },
    { code: 'hr', name: 'Hrvatski (Croatian)' },
    { code: 'cs', name: 'Čeština (Czech)' },
    { code: 'da', name: 'Dansk (Danish)' },
    { code: 'nl', name: 'Nederlands (Dutch)' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'et', name: 'Eesti (Estonian)' },
    { code: 'tl', name: 'Filipino' },
    { code: 'fi', name: 'Suomi (Finnish)' },
    { code: 'fy', name: 'Frysk (Frisian)' },
    { code: 'gl', name: 'Galego (Galician)' },
    { code: 'el', name: 'Ελληνικά (Greek)' },
    { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
    { code: 'ht', name: 'Kreyòl Ayisyen (Haitian Creole)' },
    { code: 'ha', name: 'Hausa' },
    { code: 'haw', name: 'ʻŌlelo Hawaiʻi (Hawaiian)' },
    { code: 'he', name: 'עברית (Hebrew)' },
    { code: 'hi', name: 'हिन्दी (Hindi)' },
    { code: 'hmn', name: 'Hmong' },
    { code: 'hu', name: 'Magyar (Hungarian)' },
    { code: 'is', name: 'Íslenska (Icelandic)' },
    { code: 'ig', name: 'Igbo' },
    { code: 'id', name: 'Bahasa Indonesia (Indonesian)' },
    { code: 'ga', name: 'Gaeilge (Irish)' },
    { code: 'jw', name: 'Jawa (Javanese)' },
    { code: 'kn', name: 'ಕನ್ನಡ (Kannada)' },
    { code: 'kk', name: 'Қазақ (Kazakh)' },
    { code: 'km', name: 'ខ្មែរ (Khmer)' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'ku', name: 'Kurdî (Kurdish)' },
    { code: 'ky', name: 'Кыргызча (Kyrgyz)' },
    { code: 'lo', name: 'ລາວ (Lao)' },
    { code: 'la', name: 'Latina (Latin)' },
    { code: 'lv', name: 'Latviešu (Latvian)' },
    { code: 'lt', name: 'Lietuvių (Lithuanian)' },
    { code: 'lb', name: 'Lëtzebuergesch (Luxembourgish)' },
    { code: 'mk', name: 'Македонски (Macedonian)' },
    { code: 'mg', name: 'Malagasy' },
    { code: 'ms', name: 'Bahasa Melayu (Malay)' },
    { code: 'ml', name: 'മലയാളം (Malayalam)' },
    { code: 'mt', name: 'Malti (Maltese)' },
    { code: 'mi', name: 'Māori (Maori)' },
    { code: 'mr', name: 'मराठी (Marathi)' },
    { code: 'mn', name: 'Монгол (Mongolian)' },
    { code: 'my', name: 'မြန်မာ (Myanmar)' },
    { code: 'ne', name: 'नेपाली (Nepali)' },
    { code: 'no', name: 'Norsk (Norwegian)' },
    { code: 'or', name: 'ଓଡ଼ିଆ (Odia)' },
    { code: 'ps', name: 'پښتو (Pashto)' },
    { code: 'fa', name: 'فارسی (Persian)' },
    { code: 'pl', name: 'Polski (Polish)' },
    { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
    { code: 'ro', name: 'Română (Romanian)' },
    { code: 'sm', name: 'Samoan' },
    { code: 'gd', name: 'Gàidhlig (Scots Gaelic)' },
    { code: 'sr', name: 'Српски (Serbian)' },
    { code: 'st', name: 'Sesotho' },
    { code: 'sn', name: 'Shona' },
    { code: 'sd', name: 'سنڌي (Sindhi)' },
    { code: 'si', name: 'සිංහල (Sinhala)' },
    { code: 'sk', name: 'Slovenčina (Slovak)' },
    { code: 'sl', name: 'Slovenščina (Slovenian)' },
    { code: 'so', name: 'Soomaali (Somali)' },
    { code: 'su', name: 'Basa Sunda (Sundanese)' },
    { code: 'sw', name: 'Kiswahili (Swahili)' },
    { code: 'sv', name: 'Svenska (Swedish)' },
    { code: 'tg', name: 'Тоҷикӣ (Tajik)' },
    { code: 'ta', name: 'தமிழ் (Tamil)' },
    { code: 'tt', name: 'Татар (Tatar)' },
    { code: 'te', name: 'తెలుగు (Telugu)' },
    { code: 'th', name: 'ไทย (Thai)' },
    { code: 'tr', name: 'Türkçe (Turkish)' },
    { code: 'tk', name: 'Türkmen (Turkmen)' },
    { code: 'uk', name: 'Українська (Ukrainian)' },
    { code: 'ur', name: 'اردو (Urdu)' },
    { code: 'ug', name: 'ئۇيغۇرچە (Uyghur)' },
    { code: 'uz', name: 'Oʻzbek (Uzbek)' },
    { code: 'vi', name: 'Tiếng Việt (Vietnamese)' },
    { code: 'cy', name: 'Cymraeg (Welsh)' },
    { code: 'xh', name: 'isiXhosa (Xhosa)' },
    { code: 'yi', name: 'ייִדיש (Yiddish)' },
    { code: 'yo', name: 'Yorùbá (Yoruba)' },
    { code: 'zu', name: 'isiZulu (Zulu)' }
];
