/**
 * Groq API 调用服务
 * 
 * 使用 OpenAI 兼容格式直接 fetch，无需额外 SDK。
 * 支持文本翻译（批量和单条）。
 */

import { GROQ_API_URL } from '../constants';
import { getLanguageName } from '../constants';

// ─── 类型 ─────────────────────────────────────────────────────────────────

export interface GroqTranslateResult {
    translatedText: string;
    chineseText: string;
    translations?: Record<string, string>;
    detectedLanguage: string;
}

export interface GroqBatchItem {
    id: string;
    text: string;
}

// ─── 底层调用 ──────────────────────────────────────────────────────────────

/**
 * 调用 Groq Chat Completions API
 */
async function groqChatCompletion(
    apiKey: string,
    model: string,
    systemPrompt: string,
    userPrompt: string,
    temperature: number = 0.1,
    maxTokens: number = 4096
): Promise<string> {
    const resp = await fetch(GROQ_API_URL, {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            model,
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userPrompt }
            ],
            temperature,
            max_tokens: maxTokens
        })
    });

    if (resp.status === 429) {
        throw new Error('429 RESOURCE_EXHAUSTED: Groq rate limit exceeded');
    }
    if (resp.status === 401 || resp.status === 403) {
        throw new Error(`KEY_INVALID: Groq authentication failed (${resp.status})`);
    }
    if (!resp.ok) {
        const errBody = await resp.json().catch(() => ({}));
        throw new Error(`Groq API ${resp.status}: ${errBody?.error?.message || resp.statusText}`);
    }

    const data = await resp.json();
    return (data.choices?.[0]?.message?.content || '').trim();
}

// ─── 翻译接口 ──────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a professional translation engine. You output ONLY valid JSON, never markdown, never explanations.`;

/**
 * 使用 Groq 翻译单条文本
 */
export async function groqTranslateSingle(
    apiKey: string,
    model: string,
    textToTranslate: string,
    effectiveBatchLanguages: string[],
    batchCleanupMode: boolean = false,
    customInstruction: string = ''
): Promise<GroqTranslateResult> {
    if (!textToTranslate?.trim()) {
        return {
            translatedText: '',
            chineseText: '',
            translations: effectiveBatchLanguages.reduce((acc, code) => ({ ...acc, [code]: '' }), {}),
            detectedLanguage: ''
        };
    }

    const isChineseOnly = effectiveBatchLanguages.length === 0;
    const targetLangSpecs = effectiveBatchLanguages
        .map(code => `${getLanguageName(code)} (${code})`)
        .join(', ');
    const targetLangJson = effectiveBatchLanguages
        .map(code => `"${code}": "translation in ${getLanguageName(code)}"`)
        .join(', ');

    const cleanupNote = batchCleanupMode
        ? `\nNOTE: Only remove text that EXACTLY matches these specific AI tool watermark patterns: "Made with ChatGPT", "Generated by Midjourney", "Created using DALL-E", "Made by Sora", "Made by Kling", or a line containing ONLY a social handle like "@username". DO NOT remove titles, headings, slogans, or any written content.\n`
        : '';
    const customNote = customInstruction.trim()
        ? `\nADDITIONAL USER REQUIREMENTS:\n${customInstruction.trim()}\n`
        : '';

    const userPrompt = isChineseOnly
        ? `Translate the following text into Chinese (Simplified).
Also provide the detected source language name in Chinese.
${cleanupNote}${customNote}
CRITICAL RULES:
1. Translate the COMPLETE text - do NOT skip or omit any part, especially the FIRST LINE (title/heading).
2. The first line is the TITLE and MUST be translated - never skip or remove it.
3. If the source text is already in Chinese, copy it exactly to the "chinese" field.
4. Preserve all line breaks and formatting from the original.

Return in this exact JSON format (no markdown):
{"chinese": "Chinese translation or original", "detectedLanguage": "语言名称"}

Text to translate:
"""
${textToTranslate}
"""`
        : `Translate the following text into these target languages: ${targetLangSpecs}.
Also provide the detected source language name in Chinese.
${cleanupNote}${customNote}
CRITICAL RULES:
1. Translate the COMPLETE text - do NOT skip or omit any part.
2. The first line is the TITLE and MUST be translated.
3. If the source text is already in Chinese, copy it exactly to the "chinese" field.
4. Preserve all line breaks and formatting from the original.

Return in this exact JSON format (no markdown):
{"translations": {${targetLangJson}}, "chinese": "Chinese translation or original", "detectedLanguage": "语言名称"}

Text to translate:
"""
${textToTranslate}
"""`;

    const rawResponse = await groqChatCompletion(apiKey, model, SYSTEM_PROMPT, userPrompt);

    // 解析 JSON 响应
    let translatedText = '';
    let chineseText = '';
    let detectedLanguage = '';
    let translations: Record<string, string> | undefined;
    const primaryBatchLanguage = effectiveBatchLanguages[0] || '';

    try {
        let cleanResponse = rawResponse.trim();
        if (cleanResponse.startsWith('```')) {
            cleanResponse = cleanResponse.replace(/^```[a-zA-Z]*\s*/, '').replace(/```\s*$/, '');
        }
        const parsed = JSON.parse(cleanResponse);

        if (!isChineseOnly && parsed.translations && typeof parsed.translations === 'object') {
            translations = {};
            effectiveBatchLanguages.forEach(code => {
                if (typeof parsed.translations[code] === 'string') {
                    translations![code] = parsed.translations[code];
                }
            });
        }

        if (parsed.chinese) chineseText = parsed.chinese;
        if (parsed.detectedLanguage) detectedLanguage = parsed.detectedLanguage;
    } catch {
        if (isChineseOnly) {
            chineseText = rawResponse;
        } else {
            translations = effectiveBatchLanguages.reduce(
                (acc, code) => ({ ...acc, [code]: rawResponse }),
                {} as Record<string, string>
            );
        }
    }

    if (!isChineseOnly && translations && translations[primaryBatchLanguage]) {
        translatedText = translations[primaryBatchLanguage];
    }

    if (isChineseOnly) {
        translatedText = '';
        translations = undefined;
    }

    return { translatedText, chineseText, translations, detectedLanguage };
}

/**
 * 使用 Groq 批量翻译多条文案
 * 返回与输入顺序对应的翻译结果数组
 */
export async function groqTranslateBatch(
    apiKey: string,
    model: string,
    batch: GroqBatchItem[],
    effectiveBatchLanguages: string[],
    batchCleanupMode: boolean = false,
    customInstruction: string = ''
): Promise<GroqTranslateResult[]> {
    if (batch.length === 0) return [];

    const isChineseOnly = effectiveBatchLanguages.length === 0;
    const targetLangSpecs = effectiveBatchLanguages
        .map(code => `${getLanguageName(code)} (${code})`)
        .join(', ');
    const targetLangJson = effectiveBatchLanguages
        .map(code => `"${code}": "translation in ${getLanguageName(code)}"`)
        .join(', ');

    const cleanupNote = batchCleanupMode
        ? `\nNOTE: Only remove AI watermarks like "Made with ChatGPT". DO NOT remove titles or content.\n`
        : '';
    const customNote = customInstruction.trim()
        ? `\nADDITIONAL USER REQUIREMENTS:\n${customInstruction.trim()}\n`
        : '';

    const numberedTexts = batch.map((b, i) => `--- ITEM ${i + 1} ---\n${b.text}`).join('\n\n');

    const userPrompt = isChineseOnly
        ? `Translate ${batch.length} text items into Chinese (Simplified).
Also detect the source language for each item.
${cleanupNote}${customNote}
CRITICAL RULES:
1. Translate COMPLETE text for each item including FIRST LINE (title).
2. If already Chinese, copy exactly.
3. Preserve line breaks and formatting.
4. Return a JSON array with exactly ${batch.length} objects.

Return in this exact JSON format (no markdown):
[
  {"chinese": "Chinese translation", "detectedLanguage": "语言名称"},
  ...
]

Here are the ${batch.length} items:

${numberedTexts}`
        : `Translate ${batch.length} text items into: ${targetLangSpecs}.
Also detect the source language for each item.
${cleanupNote}${customNote}
CRITICAL RULES:
1. Translate COMPLETE text for each item including titles.
2. If already Chinese, copy to "chinese" field.
3. Preserve formatting.
4. Return JSON array with exactly ${batch.length} objects.

Return in this exact JSON format (no markdown):
[
  {"translations": {${targetLangJson}}, "chinese": "Chinese translation", "detectedLanguage": "语言名称"},
  ...
]

Here are the ${batch.length} items:

${numberedTexts}`;

    const rawResponse = await groqChatCompletion(
        apiKey, model, SYSTEM_PROMPT, userPrompt,
        0.1, Math.max(4096, batch.length * 1024)
    );

    // 解析批量结果
    const primaryBatchLanguage = effectiveBatchLanguages[0] || '';
    const results: GroqTranslateResult[] = [];

    try {
        let cleanResponse = rawResponse.trim();
        if (cleanResponse.startsWith('```')) {
            cleanResponse = cleanResponse.replace(/^```[a-zA-Z]*\s*/, '').replace(/```\s*$/, '');
        }
        const parsed = JSON.parse(cleanResponse);

        if (Array.isArray(parsed)) {
            for (let i = 0; i < batch.length; i++) {
                const item = parsed[i] || {};
                let translatedText = '';
                let translations: Record<string, string> | undefined;

                if (!isChineseOnly && item.translations) {
                    translations = {};
                    effectiveBatchLanguages.forEach(code => {
                        if (typeof item.translations?.[code] === 'string') {
                            translations![code] = item.translations[code];
                        }
                    });
                    if (translations[primaryBatchLanguage]) {
                        translatedText = translations[primaryBatchLanguage];
                    }
                }

                results.push({
                    translatedText: isChineseOnly ? '' : translatedText,
                    chineseText: item.chinese || '',
                    translations: isChineseOnly ? undefined : translations,
                    detectedLanguage: item.detectedLanguage || ''
                });
            }
        }
    } catch {
        // 解析失败：所有条目标记为原始返回
        batch.forEach(() => {
            results.push({
                translatedText: '',
                chineseText: rawResponse,
                detectedLanguage: ''
            });
        });
    }

    // 补齐缺失条目
    while (results.length < batch.length) {
        results.push({
            translatedText: '',
            chineseText: '[Groq 返回结果不完整]',
            detectedLanguage: ''
        });
    }

    return results;
}
