import { getLanguageName } from '../constants'; // Needs to resolve properly

export async function smartTranslateSingleItem(
    ai: any,
    textModel: string,
    textToTranslate: string,
    effectiveBatchLanguages: string[],
    batchCleanupMode: boolean,
    customInstruction: string = ''
) {
    if (!textToTranslate || !textToTranslate.trim()) {
        return {
            translatedText: '',
            chineseText: '',
            translations: effectiveBatchLanguages.reduce((acc, code) => ({...acc, [code]: ''}), {}),
            detectedLanguage: ''
        };
    }

    const isChineseOnly = effectiveBatchLanguages.length === 0;
    const targetLangSpecs = effectiveBatchLanguages
        .map(code => `${getLanguageName(code)} (${code})`)
        .join(', ');
    const targetLangJson = effectiveBatchLanguages
        .map(code => `"${code}": "translation in ${getLanguageName(code)}"`)
        .join(', ');

    const cleanupNote = batchCleanupMode ? `\nNOTE: Only remove text that EXACTLY matches these specific AI tool watermark patterns (verbatim signatures): "Made with ChatGPT", "Generated by Midjourney", "Created using DALL-E", "Made by Sora", "Made by Kling", or a line containing ONLY a social handle like "@username". DO NOT remove titles, headings, slogans, or any written content.\n` : '';
    const customNote = customInstruction.trim() ? `\nADDITIONAL USER REQUIREMENTS:\n${customInstruction.trim()}\n` : '';

    const translatePrompt = isChineseOnly
        ? `Translate the following text into Chinese (Simplified).
Also provide the detected source language name in Chinese.
${cleanupNote}${customNote}
CRITICAL RULES:
1. Translate the COMPLETE text - do NOT skip or omit any part, especially the FIRST LINE (title/heading).
2. The first line is the TITLE and MUST be translated - never skip or remove it.
3. If the source text is already in Chinese, copy it exactly to the "chinese" field.
4. If the source text is NOT Chinese, translate it to Chinese (Simplified) for the "chinese" field.
5. Preserve all line breaks and formatting from the original.
6. Do NOT remove any content - translate everything including titles, slogans, and all body text.

Return in this exact JSON format (no markdown):
{"chinese": "Chinese translation or original if source is Chinese", "detectedLanguage": "语言名称"}

Text to translate:
"""
${textToTranslate}
"""`
        : `Translate the following text into these target languages: ${targetLangSpecs}.
Also provide the detected source language name in Chinese.
Use the language codes as keys in the JSON output.
${cleanupNote}${customNote}
CRITICAL RULES:
1. Translate the COMPLETE text - do NOT skip or omit any part, especially the FIRST LINE (title/heading).
2. The first line is the TITLE and MUST be translated - never skip or remove it.
3. If the source text is already in Chinese, copy it exactly to the "chinese" field.
4. If the source text is NOT Chinese, translate it to Chinese (Simplified) for the "chinese" field.
5. Preserve all line breaks and formatting from the original.
6. Do NOT remove any content - translate everything including titles, slogans, and all body text.

Return in this exact JSON format (no markdown):
{"translations": {${targetLangJson}}, "chinese": "Chinese translation or original if source is Chinese", "detectedLanguage": "语言名称"}

Text to translate:
"""
${textToTranslate}
"""`;

    // 429 重试逻辑
    const MAX_SINGLE_RETRIES = 3;
    let translateResponse: any = null;
    for (let attempt = 0; attempt <= MAX_SINGLE_RETRIES; attempt++) {
        try {
            translateResponse = await ai.models.generateContent({
                model: textModel,
                contents: translatePrompt
            });
            break;
        } catch (retryErr: any) {
            const is429 = retryErr?.message?.includes('429') || retryErr?.message?.includes('RESOURCE_EXHAUSTED') || retryErr?.status === 429;
            if (is429 && attempt < MAX_SINGLE_RETRIES) {
                const delay = (attempt + 1) * 5000;
                console.warn(`[翻译] 429 rate limit, retry ${attempt + 1}/${MAX_SINGLE_RETRIES} after ${delay}ms`);
                await new Promise(r => setTimeout(r, delay));
                continue;
            }
            throw retryErr;
        }
    }

    let translatedText = translateResponse?.text ?? '';
    let chineseText = '';
    let detectedLanguage = '';
    let translations: Record<string, string> | undefined;
    const primaryBatchLanguage = effectiveBatchLanguages[0] || '';

    try {
        let cleanResponse = translatedText.trim();
        if (cleanResponse.startsWith('```')) {
            cleanResponse = cleanResponse.replace(/^```[a-zA-Z]*\s*/, '').replace(/```\s*$/, '');
        }
        const parsed = JSON.parse(cleanResponse);
        if (!isChineseOnly) {
            if (parsed.translations && typeof parsed.translations === 'object') {
                translations = {};
                effectiveBatchLanguages.forEach(code => {
                    const value = parsed.translations[code];
                    if (typeof value === 'string') {
                        translations![code] = value;
                    }
                });
            } else if (parsed.translated) {
                translations = { [primaryBatchLanguage]: parsed.translated };
            }
        }
        if (parsed.chinese) {
            chineseText = parsed.chinese;
        }
        if (parsed.detectedLanguage) {
            detectedLanguage = parsed.detectedLanguage;
        }
    } catch (e) {
        if (isChineseOnly) {
            chineseText = translatedText;
        } else {
            // Fallback: put the raw response in ALL requested languages so it's not silently lost
            translations = effectiveBatchLanguages.reduce((acc, code) => ({...acc, [code]: translatedText}), {} as Record<string, string>);
        }
    }

    if (!isChineseOnly && translations && translations[primaryBatchLanguage]) {
        translatedText = translations[primaryBatchLanguage];
    }

    // 第二步：检测原文语言（补充逻辑）
    if (!detectedLanguage) {
        try {
            const detectPrompt = `What language is this text written in? Reply with only the language name in Chinese (e.g., 英语, 日语, 西班牙语, 法语, 德语, 韩语, 俄语, 阿拉伯语, etc.). Just one or two words, nothing else.\n\nText: "${textToTranslate.slice(0, 200)}"`;
            const detectResponse = await ai.models.generateContent({
                model: textModel,
                contents: detectPrompt
            });
            detectedLanguage = (detectResponse.text ?? '').trim().replace(/[。.，,\s]/g, '');
        } catch (detectError) {
        }
    }

    if (isChineseOnly) {
        translatedText = '';
        translations = undefined;
    }

    return {
        translatedText,
        chineseText,
        translations,
        detectedLanguage
    };
}
