// 预设互动语库 - 从采集数据自动生成
// 新库 (0321): 100 条 | 老库: 337 条

export interface LibraryItem {
    id: string;
    content: string;
    weight: number;
    tags: string;
    usedCount: number;
}

export interface CopywritingLibrary {
    id: string;
    name: string;
    matchRule: string;
    maxRepeat: number;
    items: LibraryItem[];
    enabled: boolean;
    color: string;
    group?: string;
}

export const LIBRARY_PRESETS: CopywritingLibrary[] = [
    {
        id: 'preset_new_0321',
        name: '互动语库01（新库0321）',
        color: '#4ade80',
        enabled: true,
        maxRepeat: 2,
        matchRule: '根据文案内容选择合适的互动语，并替换/添加到文案末尾',
        items: [
            { id: 'new_1', content: 'If you believe this prayer, don\'t forget to put Amen and pass this on to someone who needs God\'s strength today.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_2', content: 'If you believe, leave your Amen in the comments. And share this prayer with someone. I believe God will multiply your blessings.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_3', content: 'If you believe, please put "Amen" to defeat Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_4', content: 'If you believe blessings are on the way, put Amen and send this to a friend who believes too.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_5', content: 'If you believe God will never let you down, put "Amen" to silence the enemy and declare God\'s truth over your life.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_6', content: 'If you believe God can calm the storm in your life, offer an Amen! Share this with a friend who is waiting — let them know: God has not forgotten them.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_7', content: 'If you believe God\'s love and power never fail, send this to uplift someone\'s heart and whisper Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_8', content: 'If you believe in the power of this prayer, type Amen in the comments. Like and share this with someone who needs God\'s protection today. God bless you.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_9', content: 'If you believe in the power of Psalm 91, type Amen in the comments and share this prayer with someone who needs God\'s protection today.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_10', content: 'If you believe the curses have been broken, please share this with others who are under attack. Put Amen to defeat Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_11', content: 'If you love God and are not ashamed of Him, pass this prayer to someone you care about and watch what He does in your life. Don\'t forget "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_12', content: 'If you love God and are not ashamed of Him, send to your friends and see how God will work in your life. Praise Him with an Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_13', content: 'If you love God and are not ashamed of Him, share this prayer with a friend and you will see what God will do. If you believe it, echo the Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_14', content: 'If you love God and are not ashamed of Him, put "Amen" and share this prayer with a friend and you will see what God will do.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_15', content: 'If you love God and are not ashamed of Him, share this prayer with your friends and see how God will work in your life. If you need God to guide your daily life, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_16', content: 'If you love God and are not ashamed of Him, with a grateful Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_17', content: 'If you love God and are not ashamed of Him, Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_18', content: 'If you love God, put Amen and share this to someone you love.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_19', content: 'If you love the One who died on the cross to save our souls, a big Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_20', content: 'If you trust Him, put Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_21', content: 'If you trust this prayer, drop "Amen" to silence Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_22', content: 'If you trust God with all your heart, Amen and don\'t forget to pass this to inspire others.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_23', content: 'If you trust God to make a way, put "Amen" and share this to inspire others.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_24', content: 'If you trust God to watch over your night, drop "Amen" and share this prayer with faith. Dear God, bless those who echo Amen with rest, safety, and comfort.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_25', content: 'If you trust God\'s arrangement, whisper Amen. Dear God, please bring peace to the one who sends this and puts forth a devoted Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_26', content: 'If you depend on Him, put Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_27', content: 'If you rely on God, put "I do."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_28', content: 'If you choose Jesus above all, put Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_29', content: 'If Jesus protects you daily, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_30', content: 'If God is with you, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_31', content: 'If you\'re grateful for your other half, put "Amen" and pass this on to him.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_32', content: 'If you\'re grateful to God, Amen and you will see what God will do in your life!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_33', content: 'If you\'re grateful and not ashamed of Jesus, send this to another godly sister. Dear God, please open doors for the person who shares this and puts Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_34', content: 'If God has been good to you, shout out Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_35', content: 'If God has been good to you, put "Amen" to disappoint Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_36', content: 'If God has never failed you this year, put "Amen" to claim your faith.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_37', content: 'If God has blessed you today, put Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_38', content: 'If God is good to you, praise Him! Put "Amen" to put Satan to shame!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_39', content: 'If God is really important in your life, put "Amen" and send this to someone you care about.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_40', content: 'If God is really important in your life, don\'t forget Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_41', content: 'Lord, I love You and I promise to share this prayer with at least one person. In the victorious name of Jesus Christ I pray, Amen. Put "Amen" to make the enemy flee from your life!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_42', content: 'Lord, I promise to share this prayer with at least one person. Put "Amen" to disappoint Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_43', content: 'My Lord, I promise to share this prayer with at least one person. In the name of Jesus, put "Amen" and believe God\'s blessing will cover this month.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_44', content: 'My Lord, I promise to share this prayer with at least one person. In the name of Jesus, disappoint Satan by putting "I love Jesus."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_45', content: 'My Lord, I promise to share this prayer with at least one person. In the name of Jesus, puts "Amen" to put Satan to shame!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_46', content: 'And I promise to send this prayer to my friends. Put "Amen" to disappoint Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_47', content: 'I promise to share this prayer with at least one person. Please open every door for everyone who puts Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_48', content: 'Put "Amen" to disappoint Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_49', content: 'Put "Amen" to put Satan to shame!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_50', content: 'Put "Amen" and let the devil be disappointed.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_51', content: 'Put Amen, and let Satan be put to shame.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_52', content: 'Put "God is great" to declare victory!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_53', content: 'Put Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_54', content: 'Imagine this, when you share this verse, Jesus smiles at you. Put Amen and let Satan be disappointed.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_55', content: 'In the name of Jesus, disappoint Satan by putting "I love Jesus."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_56', content: 'Let\'s disappoint the enemy today by putting "God is first."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_57', content: 'Don\'t forget Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_58', content: 'Lord, open doors for everyone who faithfully puts Amen and shares this. In the name of Jesus Christ we pray, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_59', content: 'Dear God, please open all doors for the person who passes this along and puts Amen to put Satan to shame.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_60', content: 'Dear God, please protect those who read this message and are willing to offer an Amen in 2026!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_61', content: 'If you\'re waiting on God\'s answer, let your Amen be heard. Dear God, please open all doors for the person who passes this along and proclaims a devoted Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_62', content: 'Send it to a godly sister who needs the reminder: She\'s seen. She\'s loved. Always. Dear God, please open every door for the one who shares this and puts "Amen" to put the enemy to shame.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_63', content: 'If you are not ashamed of Jesus Christ, send this to a godly sister. Dear God, please open all doors for the person who puts Amen to shame Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_64', content: 'If you\'re not ashamed of Jesus, send this to a godly sister and remind her: God will make a way. Lord, make a way for the woman who passes this along and puts "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_65', content: 'If you\'re not ashamed of Jesus, share this with a godly sister and remind her: God is with her. Lord, please make a way for the woman who shares this message and puts "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_66', content: 'If you\'re grateful for your best friend, share this prayer to remind her how deeply loved, empowered, and cherished she is in God\'s eyes. Don\'t forget to say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_67', content: 'If you\'re praying for your daughter today, send this to her and let her know she is covered in prayer. Put "Amen" to declare protection and victory over your children\'s future.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_68', content: 'If you\'re praying for your daughter this week, send this to her as a blessing. And if you know God is good, put "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_69', content: 'God, thank You, I love You, and I promise to pass this prayer on as a blessing. If you love God and are not ashamed of Him, share this prayer with a friend. You will see God move. If you believe, please offer an Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_70', content: 'I love You, and I promise to share this prayer. May I glorify Your name, not just with my lips, but in my life. "Amen", and let the enemy be utterly disappointed today!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_71', content: 'I love You, God. I promise to share this with my family and friends. If you love God, put "Amen" and you will see what He will do in your life!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_72', content: 'I love You, and I will honor You by sharing this prayer. If you love God and are not ashamed of Him, put "Amen" and send this to someone who needs it today.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_73', content: 'God, I love You, and I promise: I will forward this prayer to my friends and put Amen to disappoint the enemy!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_74', content: 'Lord, I love You, and I promise to share this prayer with others. Even if you are busy, if you love God, please type Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_75', content: 'Lord, I love You, and I promise to share this prayer with the ones I love. Offer an Amen to see how God moves in your life.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_76', content: 'Today I promise to share this prayer with someone else. Write "God is faithful" and let His light drive out the darkness!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_77', content: 'If this prayer touches you, echo "Amen" and share it with someone you want to bless.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_78', content: 'If you are not ashamed of God, don\'t forget "Amen" and send this to someone you love.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_79', content: 'If this message touched your heart today, type Amen and share it with someone who needs this reminder of hope.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_80', content: 'If this message encouraged your heart today, type Amen and share it with someone who needs a reminder to stop worrying and start trusting. God bless you.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_81', content: 'If you agree with this prayer, type Amen in the comments. Share this with three people who need it, and save this video to return with your testimony. God bless you, and remember, this week will bless you, not break you.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_82', content: 'You are not reading this by accident. God has heard your prayer. You\'re going to be okay. Take 1 minute to send this prayer to the person you want God to bless. Put "Thank God" to disappoint Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_83', content: 'Put "Amen" and walk into this new month with faith.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_84', content: 'If you receive this prayer, type Amen in the comments. Follow for more prayers, and share this to bless someone who needs it today.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_85', content: 'Before this day ends, take one minute to share this with someone who needs encouragement. If you believe He\'s still working for your good, put "Amen" with faith and let the enemy be silenced.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_86', content: 'Save this. Come back when doubt creeps in. If you trust God, put Amen with bold faith — and watch the enemy flee.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_87', content: 'When your hand is not too busy, put Amen with bold faith — and watch the enemy flee.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_88', content: 'Those who love this prayer, put Amen, and you will see what He will do in your life.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_89', content: 'If you feel the same, Amen! Pass this prayer to someone you love and see how God will work in your life.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_90', content: 'If you\'re walking by faith, forward this and put a true Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_91', content: 'Amen if you agree.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_92', content: 'Amen if you believe.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_93', content: 'If you want God to be with you, put Amen to put Satan to shame!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_94', content: 'God, I love You, and I promise to share this. If you are thankful to God, put Amen and watch what He will do in your life.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_95', content: 'If you\'re facing a test of faith, and if you love God and aren\'t ashamed of Him, put Amen and share this prayer.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_96', content: 'Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_97', content: 'Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_98', content: 'If you depend on God, put "I do."', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_99', content: 'When you trust in God, put Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'new_100', content: 'If you want to share this prayer too, Amen.', weight: 8, tags: '', usedCount: 0 },
        ],
    },
    {
        id: 'preset_old',
        name: '互动语库02（老库）',
        color: '#22d3ee',
        enabled: true,
        maxRepeat: 2,
        matchRule: '根据文案内容选择合适的互动语，并替换/添加到文案末尾',
        items: [
            { id: 'old_1', content: 'Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_2', content: 'Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_3', content: 'Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_4', content: 'Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_5', content: 'Amen, trust in God!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_6', content: 'Amen, disappoint Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_7', content: 'Amen, and encourage others!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_8', content: 'Amen, and send this to someone who needs guidance today.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_9', content: 'Amen, if you believe it.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_10', content: 'Amen, thank God.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_11', content: '🙏 Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_12', content: 'A big Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_13', content: 'A powerful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_14', content: 'Please say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_15', content: 'Please say Amen and share.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_16', content: 'Please say Amen and send this to someone you love.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_17', content: 'Please say "Amen" and share with someone of strong faith!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_18', content: 'Please say "Amen" and let the devil be disappointed. Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_19', content: 'Please say "Amen" to disappoint Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_20', content: 'Please say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_21', content: 'Please say a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_22', content: 'Please say a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_23', content: 'Please say a faithful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_24', content: 'Please say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_25', content: 'Please say Amen loudly!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_26', content: 'Please write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_27', content: 'Please write Amen and share!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_28', content: 'Please write "Amen" and share freely.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_29', content: 'Please write a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_30', content: 'Please write a sincere "Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_31', content: 'Please write a faithful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_32', content: 'Please write "I do"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_33', content: 'Please seal it with Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_34', content: 'Please receive it with Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_35', content: 'Please sincerely write Amen below.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_36', content: 'Please take three seconds to thank God. Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_37', content: 'Please receive an Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_38', content: 'Please comment Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_39', content: 'Just say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_40', content: 'Just say Amen and share this with someone you care about.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_41', content: 'Just say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_42', content: 'Just say a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_43', content: 'Just say a sincere Amen to defeat Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_44', content: 'Just say Amen devoutly!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_45', content: 'Just write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_46', content: 'Just write "Amen" and pass it to someone you love.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_47', content: 'Just declare a faithful "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_48', content: 'Just write Amen with faith!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_49', content: 'Just sincerely say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_50', content: 'Say Amen to disappoint Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_51', content: 'Say Amen to defeat Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_52', content: 'Say "God is good!" to disappoint Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_53', content: 'Disappoint Satan by saying "God is good!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_54', content: 'Disappoint Satan by saying "God is gracious!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_55', content: 'Disappoint Satan by saying "I love Jesus."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_56', content: 'Disappoint Satan by writing "God is good!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_57', content: 'Disappoint Satan with "God is good!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_58', content: 'Disappoint Satan with "God is gracious!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_59', content: 'Disappoint Satan with "God is wonderful!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_60', content: 'Disappoint Satan with "Thank God!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_61', content: 'Disappoint Satan with "God is good!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_62', content: 'To disappoint Satan, say "God is good!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_63', content: 'Offer Amen to defeat Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_64', content: 'Sincerely say "Amen" to triumph over Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_65', content: 'Declare Amen, defeat Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_66', content: 'Speak Amen and disappoint Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_67', content: 'Say a genuine Amen to disappoint Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_68', content: 'Leave an Amen and guard your mind with God\'s Word!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_69', content: 'Don\'t forget Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_70', content: 'Don\'t forget to say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_71', content: 'Don\'t forget to say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_72', content: 'Don\'t forget Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_73', content: 'Take 10 seconds to thank God. Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_74', content: 'Take 7 seconds to thank Him. Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_75', content: 'Take 10 seconds to thank God today. Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_76', content: 'Take just 1 minute to thank God. Say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_77', content: 'Dear God, please open all doors for the person who says a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_78', content: 'Dear God, please open every door for everyone who says Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_79', content: 'Dear God, please open all doors for those who say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_80', content: 'Dear God, please open all doors for all who say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_81', content: 'Dear God, please open all doors for those who write "Amen" and pass this message on.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_82', content: 'Dear God, please open all doors for those who write Amen and share!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_83', content: 'Dear God, please fight for those who forward this message and respond with a faithful Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_84', content: 'Dear God, please open all doors for those who trust You, Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_85', content: 'Dear God, please open every door for everyone who offers Amen and shares this message.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_86', content: 'Dear God, please bless those who say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_87', content: 'Dear God, please bless those who pass this on and declare a devout Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_88', content: 'Dear God, please protect those who promise to pass this on and devoutly say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_89', content: 'Please save those who share this message and sincerely leave an Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_90', content: 'May God comfort those who say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_91', content: 'May God bless the one who says Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_92', content: 'May God bless those who say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_93', content: 'If you believe, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_94', content: 'If you believe, please say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_95', content: 'If you believe, please write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_96', content: 'If you believe, say Amen out loud.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_97', content: 'If you believe, whisper "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_98', content: 'If you believe, Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_99', content: 'If you trust Him, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_100', content: 'If you trust Him, please say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_101', content: 'If you believe He accomplishes all things, a powerful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_102', content: 'If you believe in His protection, please say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_103', content: 'If you trust His timing, please respond with Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_104', content: 'If you trust His plan, say "I do."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_105', content: 'If you believe He will handle it, please say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_106', content: 'If you believe He is working things out, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_107', content: 'If you believe in Him, please say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_108', content: 'If you believe in Him, say Amen out loud.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_109', content: 'If you believe in Him, a great big Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_110', content: 'If you believe God will take care of everything, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_111', content: 'If you believe God will take care of everything, please write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_112', content: 'If you believe God will take care of everything, don\'t forget to say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_113', content: 'If you believe God will exceed your expectations, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_114', content: 'If you believe God will carry what you cannot, respond with a sincere Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_115', content: 'If you believe God will lead you through every storm, whisper Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_116', content: 'If you believe God will restore all you\'ve lost, say a faithful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_117', content: 'If you believe God will answer your prayer, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_118', content: 'If you believe God will turn your sorrow into joy, proclaim a faithful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_119', content: 'If you believe God will open every door for you in 2026, say Amen loudly.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_120', content: 'If you believe God will never let you down, please say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_121', content: 'If you believe God will never let you down, please write "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_122', content: 'If you believe God will never let you down, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_123', content: 'If you believe God will never let you down, write "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_124', content: 'If you believe no one can close the door God has opened, please say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_125', content: 'If you believe no one can shut the door God has opened, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_126', content: 'If you believe no one can shut the door God has opened, write a "true Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_127', content: 'If you believe God is opening a new door in your life that no one can shut, say "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_128', content: 'If you believe God is almighty, please say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_129', content: 'If you believe God\'s timing is perfect, say a devout Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_130', content: 'If you believe God\'s plan is perfect, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_131', content: 'If you believe in God\'s wonderful plan, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_132', content: 'If you believe God\'s timing is never too late, share a sincere Amen below.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_133', content: 'If you believe God can do the impossible, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_134', content: 'If you believe God can accomplish the impossible, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_135', content: 'If you believe God is greater than fear, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_136', content: 'If you believe God has heard your prayer, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_137', content: 'If you believe no one can stop God\'s plan for your life, say a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_138', content: 'If you believe nothing can stop God\'s plan for you, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_139', content: 'If you believe all things are possible with God, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_140', content: 'If you believe in the power of prayer, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_141', content: 'If you believe prayer can change everything, say Amen firmly!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_142', content: 'If you believe prayer can change things, say a firm Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_143', content: 'If God has been good to you, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_144', content: 'If God has been good to you, write a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_145', content: 'If God has been good to you, say Amen and share.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_146', content: 'If God has been good to you, "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_147', content: 'If God has been good to you, praise Him, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_148', content: 'If God has been good to you, write a sincere "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_149', content: 'If God has never let you down, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_150', content: 'If God has never let you down, write a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_151', content: 'If God has never let you down, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_152', content: 'If God has never let you down, please say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_153', content: 'If God has ever answered your prayers, write a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_154', content: 'If God has saved your life many times, praise God, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_155', content: 'If God is important in your life, say a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_156', content: 'If God is important in your life, write a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_157', content: 'If God is important in your life, Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_158', content: 'If God has helped you in your life, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_159', content: 'If God is the reason you\'ve made it this far, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_160', content: 'If God is the center of your life, a firm Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_161', content: 'If God is your source, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_162', content: 'If God is the strength that keeps you going, Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_163', content: 'If God is with you, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_164', content: 'If God has shown His faithfulness, whisper: Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_165', content: 'If God has blessed you today, write "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_166', content: 'If you depend on God, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_167', content: 'If you depend on God, say "I do"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_168', content: 'If you depend on God, write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_169', content: 'If you depend on God, write "I do"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_170', content: 'If you depend on God, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_171', content: 'If you depend on God, write a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_172', content: 'If you depend on God, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_173', content: 'If you depend on God, proclaim Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_174', content: 'If you depend on God, say "I do"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_175', content: 'If you depend on God in 2026, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_176', content: 'If you believe in Him with all your heart, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_177', content: 'If you believe in Him wholeheartedly, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_178', content: 'If you believe in Him with all your heart, write a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_179', content: 'If you believe in Him wholeheartedly, sincerely say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_180', content: 'If you trust Him with all your heart, write "Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_181', content: 'If you truly believe in Him with all your heart, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_182', content: 'If you trust God with all your heart, offer your Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_183', content: 'If you truly and completely trust God, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_184', content: 'If you fully believe in Him, say a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_185', content: 'If you love the One who died on the cross to save our souls, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_186', content: 'If you love the Lord who died on the cross to save our souls, say "Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_187', content: 'If you love the Lord who was crucified to save us, leave an "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_188', content: 'If you love the One who died on the cross to save our souls, write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_189', content: 'If you love God and are not ashamed of Him, forward this. You will see what God will do, and sincerely say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_190', content: 'If you love God and are not ashamed of Him, respond with a sincere Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_191', content: 'If you love God and are not ashamed of Him, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_192', content: 'If you love God and are not ashamed of Him, declare a faithful Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_193', content: 'If you love God and are not ashamed of Him, say "God is good!" to disappoint Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_194', content: 'If you love Jesus and are not ashamed of Him, write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_195', content: 'If you follow Jesus and are not ashamed of Him, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_196', content: 'If you trust God, say "I do!"', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_197', content: 'If you trust God, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_198', content: 'If you trust God to do the impossible for you, write "Amen" and disappoint the devil. Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_199', content: 'If you trust Him, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_200', content: 'If you trust Him, say "Amen" out loud!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_201', content: 'If you trust Him, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_202', content: 'If you trust Him, write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_203', content: 'If you trust God over fear, write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_204', content: 'If you have faith in Him, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_205', content: 'If you trust God in all things, offer your Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_206', content: 'If you feel God has been good to you, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_207', content: 'If you feel God has been protecting you, put an Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_208', content: 'If you feel God has been protecting you since birth, take a moment to thank Him.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_209', content: 'If you feel God\'s presence with you, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_210', content: 'If you feel the power of prayer, respond with Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_211', content: 'If you are thankful for Jesus, write a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_212', content: 'If you are grateful for His protection, type "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_213', content: 'If you entrust your future to Him, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_214', content: 'If you credit your entire life to God, thank Him with a grateful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_215', content: 'If you give it to God, say a big Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_216', content: 'If you receive restoration, write "I receive."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_217', content: 'If you are still grateful today, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_218', content: 'If you want to live in truth today, say "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_219', content: 'If you choose faith over fear today, write "Faith."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_220', content: 'If you choose to be brave today, write "I do."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_221', content: 'If you refuse to let fear hold you back and answer God\'s call, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_222', content: 'If you are grateful for another chance today, say Amen and pass this blessing on.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_223', content: 'If you choose to trust rather than hold on alone today, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_224', content: 'If you are going through a test of faith, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_225', content: 'If you are waiting for His divine plan, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_226', content: 'If you are learning to trust, whisper: I am waiting.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_227', content: 'If you are ready to release that burden today, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_228', content: 'If you have accepted Him as your Savior, say a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_229', content: 'If you can persevere through the trial, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_230', content: 'If you can pray harder and not give up, sincerely say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_231', content: 'If you can trust God in every "lion\'s den," say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_232', content: 'If you are still sowing and waiting, this promise is for you.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_233', content: 'If you hold on to His promises, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_234', content: 'If you have weathered storms before, say "God is good."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_235', content: 'If you know God is always with you, "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_236', content: 'If you know God is with you in this season, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_237', content: 'If you have seen God exceed your expectations, say Amen out loud.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_238', content: 'If you have ever seen God make a way, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_239', content: 'If this is for you, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_240', content: 'If this is for you, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_241', content: 'If this touches you, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_242', content: 'If this message inspires you, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_243', content: 'If this message means something to you, write Amen and share it with someone who needs this reminder now.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_244', content: 'If this was prepared for you, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_245', content: 'If this prayer was meant for you, write Amen. Don\'t bear it alone — share with someone who needs grace today.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_246', content: 'If you want your name written in the Book of Life, write "Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_247', content: 'If you believe we are living in the last days and the King is coming soon, write "Amen" and share this with someone you care about.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_248', content: 'If you believe Jesus will return, Amen, and share this message with more people.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_249', content: 'If you believe Jesus is the only one who can save you from hell, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_250', content: 'If you still believe in God, write "Amen" to disappoint Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_251', content: 'If you still believe in Jesus, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_252', content: 'If God has helped you in your life, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_253', content: 'If you believe God has always been protecting you, share this verse with someone you care about and don\'t forget to say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_254', content: 'If you believe God made you stronger than yesterday, write "Amen" and share this blessing with a sister.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_255', content: 'If you believe God is doing this in you, receive it with Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_256', content: 'If you believe God can still make a way, write a genuine Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_257', content: 'If your hands aren\'t too busy, I love God.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_258', content: 'If you agree, say Amen and disappoint Satan.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_259', content: 'If you agree, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_260', content: 'If you agree, write "Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_261', content: 'If you agree, express your love for Jesus with Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_262', content: 'If you owe your entire life to God, thank Him with a grateful heart, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_263', content: 'If you are one of them, Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_264', content: 'If you are one of them, proclaim a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_265', content: 'If God has never let you down, write "Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_266', content: 'If God has been good to you, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_267', content: 'If God is important in your life, Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_268', content: 'If God has helped you in your life, write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_269', content: 'I triple dare you to write "God is good"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_270', content: 'I triple dare you to write "God is gracious"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_271', content: 'I triple dare you to write "I love Jesus"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_272', content: 'I triple dare you to write "God is wonderful"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_273', content: 'I triple dare you to write "Jesus is still King"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_274', content: 'I strongly encourage you to write "God is good"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_275', content: 'I strongly encourage you to write "I love Jesus"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_276', content: 'I sincerely hope you write "God is good"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_277', content: 'I solemnly ask you to write "God is good"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_278', content: 'Can I get an Amen?', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_279', content: 'Could I get an Amen?', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_280', content: 'Can I get an "Amen"?', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_281', content: 'For those who say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_282', content: 'For those who sincerely say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_283', content: 'Your "Amen" today will touch someone\'s life.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_284', content: 'Your Amen today will touch someone\'s life.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_285', content: 'Pass it on, remind more people of the consequences of rejecting God, and don\'t forget to say a sincere Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_286', content: 'Pass this message to remind others to stay ready, and whisper Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_287', content: 'Let\'s spread God\'s love together, share this prayer!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_288', content: 'Forward this, you will see what God will do, and say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_289', content: 'Forward this message and faithfully respond with Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_290', content: 'Forward this, you will see what God will do, and sincerely say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_291', content: 'Trust Him, say Amen out loud, and share with someone in need.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_292', content: 'And firmly respond "Yes!" Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_293', content: 'And say a sincere "Amen."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_294', content: 'And write a faithful Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_295', content: 'Please offer an Amen and share with someone of firm faith!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_296', content: 'Offer a loyal Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_297', content: 'Say Amen in faith!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_298', content: 'Write Amen with faith!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_299', content: 'Thank Him with a grateful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_300', content: 'Say Amen by faith!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_301', content: 'If you believe in God\'s power in every area in 2026, say a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_302', content: 'If you believe in God, write "God is good."', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_303', content: 'Type Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_304', content: 'Just write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_305', content: 'Only those who have faith in Him will say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_306', content: 'Only those who have faith in Him will write "Amen"!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_307', content: 'If you are willing to pray harder and not give up, then Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_308', content: 'If you believe in God, say Amen and watch the enemy flee.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_309', content: 'If you trust Him with all your heart, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_310', content: 'If you need this reminder right now, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_311', content: 'Thank God!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_312', content: 'Say Amen out loud!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_313', content: 'Drop Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_314', content: 'Speak a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_315', content: 'Write a big Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_316', content: 'Write a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_317', content: 'Write a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_318', content: 'Write a true Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_319', content: 'Write a faithful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_320', content: 'Amen! If you are willing to stand firm for Christ, boldly share this verse!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_321', content: 'Amen! Write Amen to defeat Satan!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_322', content: 'If you believe no one can close the door God has opened, write Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_323', content: 'If you believe in God\'s wonderful plan, offer a genuine Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_324', content: 'If you believe God\'s timing is perfect, offer a sincere Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_325', content: 'If you believe God will carry what you can\'t, respond with a genuine Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_326', content: 'If you believe God will restore all you\'ve lost, say a faithful Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_327', content: 'If you believe God has a perfect plan for you, write Amen and share.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_328', content: 'If you believe God will never let you down, say Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_329', content: 'If you believe God is working behind the scenes, Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_330', content: 'If you believe God can turn your sorrow into joy, say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_331', content: 'God, I love You, please open all doors for those who say Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_332', content: 'If you believe in God even when you don\'t understand, say a sincere Amen!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_333', content: 'God is good!', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_334', content: 'If you believe Jesus came for you, type "Amen." Like and share to remind someone they are not forgotten.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_335', content: 'If you believe God is opening a new door in your life that no one can shut, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_336', content: 'If you believe God will never let you down in 2026, write Amen.', weight: 8, tags: '', usedCount: 0 },
            { id: 'old_337', content: 'If you believe God will open every door for you in 2026, write Amen.', weight: 8, tags: '', usedCount: 0 },
        ],
    },
];
